image: docker/compose

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - mvbureev
  before_script:
    - ls -lsa
    - docker info
    - docker-compose version
    - docker-compose config
  script:
    - docker-compose pull
    - docker-compose build

deploy:
  stage: deploy
  tags:
    - mvbureev
  before_script:
    - docker-compose ps
  script:
    - docker-compose up -d
